"""

Revision ID: 6bdffc13b740
Revises: ddeb55e6c1c9
Create Date: 2025-08-19 18:16:29.130313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdffc13b740'
down_revision: Union[str, None] = 'ddeb55e6c1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('specialization', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developers', 'specialization')
    # ### end Alembic commands ###
