[project]
name = "server"
version = "0.0.1"
dependencies = [
    "asyncpg==0.30.0",
    "fastapi[standard]==0.115.8",
    "sqlalchemy==2.0.41",
    "pydantic_settings==2.10.1",

]

[tool.uv]
package = false